# Generated by Django 5.0.3 on 2024-03-18 18:27

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator(message='Email must be from example.com domain')])),
                ('phoneNumber', models.CharField(max_length=20, validators=[app.models.validate_phone_number], verbose_name='Номер телефона')),
                ('salary', models.BigIntegerField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('image', models.ImageField(upload_to='job/')),
                ('jobTitle', models.CharField(max_length=255, verbose_name='Название работы')),
                ('minSalary', models.BigIntegerField(verbose_name='Минимальная зарплата')),
                ('maxSalary', models.BigIntegerField(verbose_name='Максимальная зарплата')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('job', models.ManyToManyField(to='app.job')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
