# Generated by Django 5.0.3 on 2024-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employees',
        ),
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(to='app.employee'),
        ),
    ]
